name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  #Verify docker file quality 
  docker_lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
#     - name: send message using with
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: |
#           The ${{ github.event_name }} event triggered second step.
#           show the github variable ref: ${{ github.ref }}
#           show the github variable commit: ${{ github.sha }}
#           show the github variable ref: {{ commit.ref }}
#           show the github variable commit: {{ commit.sha }}
#           Commit Message: ${{ github.event.head_commit.message }}
        
 
 #Build docker image
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag easy-pay:$(date +%s)
      
    
          


